---
- hosts: webserver
  tasks:
  -name: gather_facts
   action: ec2_facts
    - name: Terminate EC2 instance
      local_action:
         module: ec2
         instance_ids: [`i-0cb2e8914bb3b26bd`]
         region: ap-south-1
         state: stopped
